EXAM/EXAM/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

SchoolCBT/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("profiles.urls")),
    path("", include("exams.urls")),
    path("admin/", admin.site.urls),
    # path('__reload__/', include('django_browser_reload.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exams/urls.py
from django.urls import path
from . import views

app_name = 'exams'

urlpatterns = [
    path('', views.home, name='home'),
    path('upload-questions/', views.upload_questions_view, name='upload-questions'),
    path('bulk-upload/<int:exam_id>/<int:subject_id>/', views.bulk_upload, name='bulk-upload'),
    path('success/', views.success, name='success'),
    path('not-in-time/', views.not_in_time, name='not-in-time'),
    path('ui-test/', views.ui_test, name='ui_test'),
    path('add-exam', views.add_exam, name='add-exam'),
    # path('admin-profile/', views.admin_profile, name='admin-profile'),
    # path('teacher-profile/', views.teacher_profile, name='teacher-profile'),
    # path('student-profile/', views.student_profile, name='student-profile'),
    path('answer-sheet/', views.answer_sheet, name='answer-sheet'),
    path('finish/', views.finish, name='finish'),
    path('exam/', views.exam, name='exam'),

    path('add-exam/', views.add_exam, name='add-exam'),
    path('exams/', views.exams, name='exams'),

    path('add-question/', views.add_question, name='add-question'),
    path('update-question/<str:pk>/', views.update_question, name='update-question'),
    path('delete-question/<str:pk>/', views.delete_question, name='delete-question'),
    path('questions/', views.questions, name='questions'),

    path('add-answer/', views.add_answer, name='add-answer'),
    path('answers/', views.answers, name='answers'),

    path('results/', views.results, name='results'),
    path('exam-details/', views.exam_details, name='exam-details'),
    path('take_test/<int:exam_id>/', views.take_test, name='take_test'),
    path('result/<int:subject_id>/', views.view_result, name='result'),
    path('report/<int:subject_id>/', views.generate_report, name='generate_report'),
]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('update-student/', views.update_student, name = 'update-student'),
    path('login/', views.Login, name = 'login'),
    path('logout/', views.Logout, name = 'logout'),
    path('admin-dashboard/', views.admin_dashboard, name = 'admin-dashboard'),
    path('teacher-dashboard/', views.teacher_dashboard, name = 'teacher-dashboard'),
    path('student-dashboard/', views.student_dashboard, name = 'student-dashboard'),
    path('students/', views.students, name = 'students'),
    path('staffs/', views.staffs, name = 'staffs'),
    path('subjects/', views.subjects, name = 'subjects'),
    path('levels/', views.levels, name = 'levels'),
    path('profiles/', views.profiles, name = 'profiles')
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import F
from django.db import transaction


class User(AbstractUser):
    is_teacher = models.BooleanField(default= False, null=True,blank=True)
    is_student = models.BooleanField(default= False, null=True,blank=True)
    is_support = models.BooleanField(default= False, null=True,blank=True)
    def __str__(self):
        return f'{self.username}'

class Level(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class StudentProfile(models.Model):
    years=(('2023','2023'),('2024','2024'),('2025','2025'),('2026','2026'))

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    admission_number = models.CharField(max_length=255, null=True, blank=True, unique=True)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    year_of_admission = models.CharField(max_length=255, choices = years)
    address = models.TextField(max_length=1000, null=True, blank=True)
    level = models.ForeignKey(Level, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f"{self.full_name}"

    @transaction.atomic
    def save(self, *args, **kwargs):
        if not self.admission_number:
            # Generate a unique admission number if not provided
            last_student = StudentProfile.objects.order_by('-id').first()
            last_enrollment_number = 0
            if last_student:
                # Safely parse the last admission number
                last_enrollment_number = int(last_student.admission_number.split('/')[-1])

            # Generate a new admission number
            self.admission_number = f"FSTC/{self.year_of_admission}/{last_enrollment_number + 1}"
        
        super(StudentProfile, self).save(*args, **kwargs)


# class StudentProfile(models.Model):
#     years=(('2023','2023'),('2024','2024'),('2025','2025'),('2026','2026'))

#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', null=True)
#     admission_number = models.CharField(max_length = 255, null=True, blank=True)
#     full_name = models.CharField(max_length=255)
#     year_of_admission = models.CharField(max_length=255, choices = years)
#     address = models.TextField(max_length=1000)
#     level = models.ForeignKey(Level, on_delete=models.CASCADE)
    
#     def __str__(self):
#         return f"{self.full_name}"
    
#     def save(self, *args, **kwargs):
#         if not self.admission_number:
#             # Generate a unique enrollment number
#             last_student = StudentProfile.objects.order_by('-id').first()
#             if last_student:
#                 last_enrollment_number = int(last_student.admission_number.split(' ')[-1])
#             else:
#                 last_enrollment_number = 0
#             self.admission_number = f"FSTC/{self.year_of_admission}/{last_enrollment_number + 1}"
#         super(StudentProfile, self).save(*args, **kwargs)

class TeacherProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='tprofile', null=True)
    staff_number = models.CharField(max_length = 255, null=True)
    full_name = models.CharField(max_length=255)
    address = models.TextField(max_length=1000)
    def __str__(self):
        return f"{self.full_name}"
    
    def save(self, *args, **kwargs):
        if not self.staff_number:
            # Generate a unique enrollment number
            last_student = StudentProfile.objects.order_by('-id').first()
            if last_student:
                last_enrollment_number = int(last_student.staff_number.split(' ')[-1])
            else:
                last_enrollment_number = 0
            self.staff_number = f"FSTC/STAFF/{last_enrollment_number + 1}"
        super(StudentProfile, self).save(*args, **kwargs)

class AdminProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='aprofile', null=True)
    full_name = models.CharField(max_length=255)
    address = models.TextField(max_length=1000)
    def __str__(self):
        return f"{self.full_name}"

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from profiles.models import User, StudentProfile
from django.forms import ModelForm

class RegisterationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-2 px-2 rounded-lg focus:outline-none focus:border-blue-500'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-2 px-2 rounded-lg focus:outline-none focus:border-blue-500'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full p-2 border rounded-lg focus:outline-none focus:border-blue-500'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full p-2 border rounded-lg focus:outline-none focus:border-blue-500'
    }))

class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = ['full_name', 'level']  

    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Full Name',
        'class': 'w-full py-2 px-2 rounded-lg focus:outline-none focus:border-blue-500 border m-4'
    }))


# class StudentProfileForm(forms.ModelForm):
#     class Meta:
#         model = StudentProfile
#         fields = ['admission_number', 'full_name', 'year_of_admission', 'address', 'level']

#     # Apply Tailwind classes to widgets
#     admission_number = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Admission Number',
#         'class': 'w-full py-2 px-2 rounded-lg focus:outline-none focus:border-blue-500'
#     }))
    
#     full_name = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Full Name',
#         'class': 'w-full py-2 px-2 rounded-lg focus:outline-none focus:border-blue-500'
#     }))

#     year_of_admission = forms.ChoiceField(widget=forms.TextInput(attrs={
#         'placeholder': 'Full Name',
#         'class': 'w-full p-2 border border-gray-300 rounded-md'
#     }))

#     address = forms.Textarea(widget=forms.TextInput(attrs={
#         'placeholder': 'Full Name',
#         'class': 'w-full p-2 border border-gray-300 rounded-md'
#     }))
    
#     level = forms.ChoiceField(widget=forms.TextInput(attrs={
#         'placeholder': 'Full Name',
#         'class': 'w-full p-2 border border-gray-300 rounded-md'
#     }))

profiles/views.py
from django.shortcuts import render, redirect
from  profiles.forms import RegisterationForm, StudentProfileForm
from .models import StudentProfile, TeacherProfile, AdminProfile, Level
from exams.models import Subject, Question, Answer, Result, Exam, SchoolInfo
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def students(request):
    students = StudentProfile.objects.all()
    context = {
        'students':students,
    }
    return render(request, 'data/students.html', context)

def staffs(request):
    staffs = TeacherProfile.objects.all()
    context = {
        'staffs':staffs,
    }
    return render(request, 'data/staffs.html', context)

def subjects(request):
    subjects = StudentProfile.objects.all()
    context = {
        'subjects':subjects,
    }
    return render(request, 'data/subjects.html', context)

def levels(request):
    levels = Level.objects.all()
    context = {
        'levels':levels,
    }
    return render(request, 'data/classes.html', context)


def admin_dashboard(request):
    return render(request, 'dashboards/admin_dashboard.html')

def teacher_dashboard(request):
    return render(request, 'dashboards/teacher_dashboard.html')

def student_dashboard(request):
    student = request.user.profile
    exam = Exam.objects.filter(level = student.level, completed = False)[0]
    context = {
        'student':student,
        'exam':exam
    }
    return render(request, 'dashboards/student_dashboard.html', context)

def Login(request):
    school_info = SchoolInfo.objects.all()[0]

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username =username, password = password)
        if user is not None and user.is_active:
            login(request,user)
            if request.user.is_support:
                return redirect('profiles:admin-dashboard')
            
            if request.user.is_teacher:
                return redirect('profiles:teacher-dashboard')
            
            if request.user.is_student:
                # return redirect('profiles:student-dashboard')
                return redirect('exams:exam')
        else:
            return redirect('profiles:signup')
    else:
        context = {
            'school_info':school_info
        }
        return render(request, 'accounts/login.html', context)
    

def Logout(request):
    logout(request)
    return redirect('profiles:login')

def signup(request):
    if request.method == 'POST':
        form = RegisterationForm(request.POST)
        if form.is_valid():
            my_user = form.save(commit = False)
            my_user.is_student = True
            my_user.save()
            StudentProfile.objects.create(user = my_user, year_of_admission='2023')
            login(request,my_user)
            return redirect('profiles:update-student')
        else:
            return redirect('profiles:signup')
    else:
        form = RegisterationForm()
        context = {
            'form':form,
        }

    return render(request, 'accounts/signup.html', context)

def update_student(request):
    stdnt = StudentProfile.objects.get(user = request.user)
    if request.method == 'POST':
        form = StudentProfileForm(request.POST, instance=stdnt)
        if form.is_valid():
            student = form.save()
            messages.success(request, f'student {student.full_name} successifully updated')
            return redirect('profiles:student-dashboard')
    else:
        form = StudentProfileForm(instance=stdnt)

    context = {
        'form':form,
    }
    return render(request, 'accounts/profile.html', context)

def profiles(request):
    level = Level.objects.get(id = 1)
    # my_students = StudentProfile.objects.filter(level = level)
    my_students = StudentProfile.objects.all()
    
   
  
    context = {
        'my_students':my_students
    }
    return render(request, 'student_profiles.html', context)


profiles/templates/dashboards/admin_dashboard.html

{% extends 'dashboards/base.html' %}

{% block content %}
    <div class="content w-full bg-gray-200 relative">
        <div class="bg-cyan-700 p-2 flex justify-between">
            <div class="lef font-bold text-gray-100 space-y-1 border p-2">
                <div class="bg-white h-1 w-6"></div>
                <div class="bg-white h-1 w-6"></div>
                <div class="bg-white h-1 w-6"></div>
            </div>
            <div class="flex items-center gap-1 px-2 text-gray-100">
                <div class="rounded-full bg-teal-900">
                    <h1 class="font-bold text-center w-8 h-8">A</h1>
                </div>
                <h2 class="font-semibold text-lg">HI, Admin</h2>
            </div>
        </div>
        {% for message in messages %}
        <div class="bg-green-500 text-white font-semibold text-center">{{message}}</div>
        {% endfor %}

        <!-- Dashboard Header -->
        <header class="mb-2">
            <h1 class="text-xl font-bold text-blue-600 p-2">Admin Dashboard</h1>
        </header>

        <!-- Dashboard Stats -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8  px-4">
            <!-- Number of Staffs -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Number of Staffs</h2>
                <p class="text-4xl text-blue-600 mt-4">30</p>
            </div>

            <!-- Number of Students -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Number of Students</h2>
                <p class="text-4xl text-blue-600 mt-4">500</p>
            </div>

            <!-- Number of Available Exams -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Available Exams</h2>
                <p class="text-4xl text-green-600 mt-4">15</p>
            </div>

            <!-- Add Exam -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Add New Exam</h2>
                <button class="mt-4 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700">Add Exam</button>
            </div>
        </div>

        <!-- Additional Dashboard Content -->
        <div class="bg-white p-6 rounded-lg shadow-lg mx-4">
            <h2 class="text-2xl font-bold text-gray-700">Recent Activity</h2>
            <p class="text-gray-600 mt-4">Details about recent exams, student registrations, etc.</p>
        </div>
        <div>
            <div>
                <div class="absolute bottom-0 left-7">
                    <h1>Footer</h1>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

profiles/templates/dashboards/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- <script src="./tailwind3.js"></script> -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;800&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <style>
        @media print {
            /* Hide everything except the report card */
            body * {
                visibility: hidden;
            }
            #report-card * {
                visibility: visible;
            }
            #report-card {
                position: absolute;
                left: -18%;
                bottom: 5px;
                top: 0;
                width: 100%;
            }
    
            /* Optionally, hide the print button */
            .text-right {
                display: none;
            }
        }
    </style>
</head>

<body>
    <div class="flex">
        <div class="bg-gray-900 text-gray-100 flex flex-col justify-between h-full overflow-auto">
            <a class="font-bold bg-cyan-800 p-3 text-xl" href="#">F.S.T.C GASHUA CBT</a>
            <hr>
            <div class="flex items-center gap-2 p-2 bg-gray-800">
                <div class="rounded-full bg-teal-900 w-10 h-10">
                    <h1 class="font-bold text-center">A</h1>
                </div>
                <div>
                    <h2 class="font-semibold text-lg">STUDENT</h2>
                    <p class="text-sm">{{request.user.email}}</p>
                </div>
            </div>
            <hr>
            <div class="w-64 h-screen bg-gray-800 text-white">
                <div class="p-4">
                    <ul>
                        {% if request.user.is_support %}
                            <div>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'profiles:admin-dashboard' %}">Dashboard</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'profiles:staffs' %}">Manage Staffs</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'profiles:students' %}">Manage Students</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:exams' %}">Exams</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:questions' %}">Questions</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:upload-questions' %}">Upload Question</a>
                                <!-- <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:answers' %}">Options</a> -->
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:results' %}">View Results</a>
                                <!-- <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="">Announcement</a> -->
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'profiles:logout' %}">Logout</a>
                                <!-- <li>
                                    <button class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out" onclick="toggleDropdown('dropdown1')">
                                        Student
                                    </button>
                                    <ul id="dropdown1" class="hidden pl-4 overflow-hidden transition-all duration-500 ease-in-out transform-gpu origin-top">
                                        <li class="p-2 hover:bg-gray-700">Sub-item 1</li>
                                        <li class="p-2 hover:bg-gray-700">Sub-item 2</li>
                                        <li class="p-2 hover:bg-gray-700">Sub-item 3</li>
                                    </ul>
                                </li>
                                <li>
                                    <button class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out" onclick="toggleDropdown('dropdown2')">
                                        Subject
                                    </button>
                                    <ul id="dropdown2" class="hidden pl-4 overflow-hidden transition-all duration-500 ease-in-out transform-gpu origin-top">
                                        <li class="p-2 hover:bg-gray-700">Sub-item 1</li>
                                        <li class="p-2 hover:bg-gray-700">Sub-item 2</li>
                                        <li class="p-2 hover:bg-gray-700">Sub-item 3</li>
                                    </ul>
                                </li>  -->
                            </div> 
                        {% endif %}

                        {% if request.user.is_teacher %}
                            <div>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:add-question' %}">Add Question</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:upload-questions' %}">Upload Question</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="">Results</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="">Announcements</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'profiles:logout' %}">Logout</a>
                                <!-- <li>
                                    <button class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out" onclick="toggleDropdown('dropdown1')">
                                        Student
                                    </button>
                                    <ul id="dropdown1" class="hidden pl-4 overflow-hidden transition-all duration-500 ease-in-out transform-gpu origin-top">
                                        <li class="p-2 hover:bg-gray-700">Sub-item 1</li>
                                        <li class="p-2 hover:bg-gray-700">Sub-item 2</li>
                                        <li class="p-2 hover:bg-gray-700">Sub-item 3</li>
                                    </ul>
                                </li> -->
                            </div> 
                        {% endif %}
                        {% if request.user.is_student %}
                            <div>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:exam' %}">Exam</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="">Result</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'exams:answer-sheet' %}">Answer Sheets</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="">message</a>
                                <a class="w-full text-left p-2 hover:bg-gray-700 focus:outline-none transition duration-300 ease-in-out inline-block" href="{% url 'profiles:logout' %}">Logout</a>
                            </div> 
                        {% endif %} 

                    </ul>
                </div>
            </div>
        </div>
        
        {% block content %}
        {% endblock %}


    </div>

    <script>
        function toggleDropdown(id) {
            // Close all open dropdowns
            var dropdowns = document.querySelectorAll('ul[id^="dropdown"]');
            dropdowns.forEach(function (dropdown) {
                if (dropdown.id !== id) {
                    dropdown.style.maxHeight = 0;
                    dropdown.style.opacity = 0;
                    dropdown.style.transform = 'scaleY(0.95)';
                    setTimeout(function () {
                        dropdown.classList.add('hidden');
                    }, 500); // Matches the transition duration
                }
            });
    
            // Toggle the clicked dropdown
            var element = document.getElementById(id);
            if (element.classList.contains('hidden')) {
                element.classList.remove('hidden');
                element.style.maxHeight = element.scrollHeight + 'px';
                element.style.opacity = 1;
                element.style.transform = 'scaleY(1)';
            } else {
                element.style.maxHeight = 0;
                element.style.opacity = 0;
                element.style.transform = 'scaleY(0.95)';
                setTimeout(function () {
                    element.classList.add('hidden');
                }, 500);
            }
        }
    </script>
</body>
</html>


profiles/templates/dashboards/student_dashboard.html
{% extends 'dashboards/base.html' %}

{% block content %}
    <div class="content w-full bg-gray-200 relative">
        <div class="bg-cyan-700 p-2 flex justify-between">
            <div class="lef font-bold text-gray-100 space-y-1 border p-2">
                <div class="bg-white h-1 w-6"></div>
                <div class="bg-white h-1 w-6"></div>
                <div class="bg-white h-1 w-6"></div>
            </div>
            <div class="flex items-center gap-1 px-2 text-gray-100">
                <div class="rounded-full bg-teal-900">
                    <h1 class="font-bold text-center w-8 h-8">A</h1>
                </div>
                <h2 class="font-semibold text-lg">HI, {{student.full_name}}</h2>
            </div>
        </div>
        {% for message in messages %}
        <div class="bg-green-500 text-white font-semibold text-center">{{message}}</div>
        {% endfor %}

        <!-- Dashboard Header -->
        <header class="mb-2">
            <h1 class="text-xl font-bold text-blue-600 p-2">Student Dashboard</h1>
        </header>

        <!-- Dashboard Stats -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8  px-4">
            <!-- Number of Students -->
            <!-- <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-xl font-bold text-gray-700">{{student.full_name}}</h2>
                <p class="text-4xl text-blue-600 mt-4">{{student.level}}</p>
            </div> -->

            <!-- Number of Available Exams -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Recent Exams</h2>
                <p class="text-4xl text-green-600 mt-4">1</p>
            </div>
            <!-- Add Exam -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Available Exams</h2>
                <button class="mt-4 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700">View</button>
            </div>
            <!-- Number of Available Exams -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-bold text-gray-700">Upcomming Exams</h2>
                <p class="text-4xl text-green-600 mt-4">5</p>
            </div>
        </div>

        <!-- Additional Dashboard Content -->
        <!-- <div class="bg-white p-6 rounded-lg shadow-lg mx-4">
            <h2 class="text-2xl font-bold text-gray-700">Recent Activity</h2>
            <p class="text-gray-600 mt-4">Details about recent exams, student registrations, etc.</p>
        </div> -->
        <div>
            <div>
                <div class="absolute bottom-0 left-7">
                    <h1>Footer</h1>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

profiles/templates/dashboards/teacher_dashboard.html
{% extends 'dashboards/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  {% block content %}
    <h1>teacher contents goes here</h1>
  {% endblock %}

</body>
</html>